# Generated by Django 3.0.2 on 2020-02-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(default='Other', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AssetModelSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Asset Model Size',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('uid', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='assets.Asset')),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='XRefProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extref_typename', models.CharField(max_length=80)),
                ('extref_value', models.CharField(max_length=80)),
                ('q_extref_typeid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'XRef Property',
                'verbose_name_plural': 'XRef Properties',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('published_on', models.IntegerField(default=1342915876000)),
                ('disclosed_on', models.IntegerField(default=1342915876000)),
                ('updated_on', models.IntegerField(default=1342915876000)),
                ('vcvssbmid', models.IntegerField(default=71885)),
                ('base_score', models.FloatField(default=7.5)),
                ('xref_properties', models.ManyToManyField(blank=True, to='assets.XRefProperty')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(default=8080)),
                ('layer7application', models.CharField(default='UnknownApplication', max_length=80)),
                ('protocol', models.CharField(default='tcp', max_length=80)),
                ('apps', models.ManyToManyField(blank=True, to='assets.App')),
                ('ip_addresses', models.ManyToManyField(blank=True, to='assets.IPAddress')),
            ],
        ),
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_addresses', to='assets.Asset')),
                ('ip_addresses', models.ManyToManyField(blank=True, to='assets.IPAddress')),
            ],
            options={
                'verbose_name': 'MAC Address',
                'verbose_name_plural': 'MAC Addresses',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=80)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_names', to='assets.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, to='assets.Vulnerability'),
        ),
        migrations.AddField(
            model_name='app',
            name='assets',
            field=models.ManyToManyField(blank=True, to='assets.Asset'),
        ),
    ]
