language: python
os:
  - linux
python:
  - "3.6"

install:
  - echo "Starting Travis"

before_script:
  - set -e
  - set -o pipefail
  - echo "Installing Dependencies..."
  - pip install -r requirements.txt
  - echo "Running Unit Tests..."
  - python -m pytest -s
  - echo "End Unit Tests..."

script:
  - echo "No build required"